version: '3.8'

services:
  frontend-blue:
    image: ${FRONTEND_IMAGE:-hyejun02/ounce-frontend:latest}
    container_name: frontend-blue
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always

  frontend-green:
    image: ${FRONTEND_IMAGE:-hyejun02/ounce-frontend:latest}
    container_name: frontend-green
    ports:
      - "3001:3000"
    env_file:
      - .env
    restart: always
